export const LOGGED_IN = "LOGGED_IN"
export const LOGOUT = "LOGOUT"
export const LOGIN = "LOGIN";
export const SIGNUP = "SIGNUP";
export const LOGGED_OUT = "LOGGED_OUT"

export const FETCH_RECIPES = "FETCH_RECIPES"
export const FETCH_RECIPE_SHOW = "FETCH_RECIPE_SHOW"
export const FETCH_TO_CREATE_RECIPE = "FETCH_TO_CREATE_RECIPE"
export const FETCH_TO_UPDATE_RECIPE = "FETCH_TO_UPDATE_RECIPE"

export const FETCH_CATEGORIES = "FETCH_CATEGORIES" 

export const FETCH_TO_ADD_INGREDIENT = "FETCH_TO_ADD_INGREDIENT"